# SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-or-later)
#
# This file configures the Zephyr project for the LuDLC echo sample.
# It enables necessary kernel features, UART communication, logging,
# and LuDLC module specific options.
#
# Copyright (C) 2025-2026 Andrey VOLKOV <andrey@volkov.fr> & LuDLC Contributors
#
# This file is licensed under either the Apache License, Version 2.0
# or the GNU General Public License, version 2 or (at your option)
# any later version.

# Enable kernel features
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=1024
CONFIG_THREAD_NAME=y
CONFIG_HEAP_MEM_POOL_SIZE=4096

# Enable UART
CONFIG_SERIAL=y
CONFIG_UART_CONSOLE=n
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_UART_USE_RUNTIME_CONFIGURE=y

# Enable logging
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3

# Enable LuDLC Module Kconfig options
CONFIG_LUDLC=y
CONFIG_LUDLC_SERIAL_CONN=y
CONFIG_LUDLC_STATIC_SERIAL_CONN=y
CONFIG_LUDLC_STATIC_SERIAL_CONN_NUM=1

# Sample behavior options
CONFIG_LUDLC_ECHO_PERIODIC_TX=y

CONFIG_DEBUG_OPTIMIZATIONS=y
